#############################################
# Browsie can handle multiple arguements all
# that is required is that each email have
# corresponding password, and that each
# argument have a space followed by a '-'
# followed by another space, then the argument
#
# If you don't have one or both of these accounts
# delete out the keywords and arguments alltogether.
#############################################
FACEBOOK_EMAIL: 
 - yourFacebook@email.here
 - optional Second email here [repeat as necessary]
FACEBOOK_PASSWORD: 
 - yourFacebookPassW0rdHere!
 - option password for second email [repeat as necessary]
OUTLOOK_EMAIL: 
 - yourOutlook@email.here
 - optional Second email here [repeat as necessary]
OUTLOOK_PASSWORD: 
 - yourOutlookPasswordHere!
 - option password for second email [repeat as necessary]
